# Generated by Django 5.1.7 on 2025-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashCard', '0002_flashcarddeck_cardcount_flashcarddeck_duecards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
    ]
