# Generated by Django 5.1.7 on 2025-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashCard', '0004_flashcarddeck_sucess_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
