# Generated by Django 5.1.7 on 2025-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashCard', '0005_quizquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(default='Question'),
            preserve_default=False,
        ),
    ]
