# Generated by Django 5.1.7 on 2025-06-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashCard', '0006_quizquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correctAnswer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
