# Generated by Django 5.1.7 on 2025-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupStudy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='joined_at',
            field=models.TimeField(null=True),
        ),
    ]
