# Generated by Django 5.1.7 on 2025-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupStudy', '0003_grouptask_sharedstudyplanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedstudyplanner',
            name='status',
            field=models.CharField(choices=[('NOT STARTED', 'Not Started'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT STARTED', max_length=20),
        ),
    ]
