# Generated by Django 5.1.7 on 2025-06-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupStudy', '0005_grouptask_complexity_alter_sharedstudyplanner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
