# Generated by Django 5.1.7 on 2025-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupStudy', '0006_grouptask_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='complexity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20),
        ),
    ]
