# Generated by Django 5.1.7 on 2025-06-12 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField(blank=True, null=True)),
                ('created_at', models.TimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('NOT_PENDING', 'Not Started'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='NOT_PENDING', max_length=20)),
                ('created_at', models.TimeField()),
                ('assign_t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyPlanner.subject')),
            ],
        ),
    ]
