# Generated by Django 5.1.7 on 2025-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlanner', '0002_alter_subject_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='assign_t',
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='NOT_STARTED', max_length=20),
        ),
    ]
