# Generated by Django 5.1.7 on 2025-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlanner', '0003_remove_topic_assign_t_alter_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateField(),
        ),
    ]
