# Generated by Django 5.1.7 on 2025-06-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PromordoTimer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='start_time',
        ),
    ]
