# Generated by Django 5.1.7 on 2025-06-26 07:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromordoTimer', '0005_pomodorosession_audionotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promodro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='PromordoTimer.pomodorosession')),
            ],
        ),
        migrations.CreateModel(
            name='PromodroStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalSession', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(editable=False, max_length=10)),
                ('promodro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promodro_stats', to='PromordoTimer.pomodorosession')),
            ],
        ),
    ]
