# Generated by Django 5.1.7 on 2025-06-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromordoTimer', '0006_notes_promodrostat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
